src/main/java/ru/netlly/technologymap/domain/Purpose.java
package ru.netlly.technologymap.domain;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "PURPOSE")
public class Purpose implements Serializable, Convertible{
    private Long id;
    private String purposeName;
    private Set<Detergent> detergents = new HashSet<Detergent>();

    public Purpose() {
    }

    public Purpose(String purposeName) {
        this.purposeName = purposeName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "PURPOSE_NAME")
    public String getPurposeName() {
        return purposeName;
    }

    public void setPurposeName(String purposeName) {
        this.purposeName = purposeName;
    }

    @ManyToMany
    @JoinTable(name = "PURPOSE_DETERGENT_RELATION",
            joinColumns = @JoinColumn(name = "PURPOSE_ID"),
            inverseJoinColumns = @JoinColumn(name = "DETERGENT_ID"))
    public Set<Detergent> getDetergents() {
        return detergents;
    }

    public void setDetergents(Set<Detergent> detergents) {
        this.detergents = detergents;
    }

    @Transient
    public List<Detergent> getDetergentsAsList() {
        return new ArrayList<Detergent>(detergents);
    }

    public String toString() {
        return "Purpose{" +
                "id=" + id +
                ", purposeName='" + purposeName + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Purpose purpose = (Purpose) o;

        return new EqualsBuilder()
                .append(id, purpose.id)
                .append(purposeName, purpose.purposeName)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(id)
                .append(purposeName)
                .toHashCode();
    }
}

src/main/webapp/WEB-INF/flows/purposes/add.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">


    <ui:define name="content">
        <h1>#{msg['label_purpose_add_title']}</h1>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel for="purposeName">#{msg['label_purpose_name']}
                </h:outputLabel>
                <p:inputText id="purposeName" value="#{purposeAddBean.purpose.purposeName}"/>
            </h:panelGrid>
            <h3>#{msg['label_purpose_detergents']}:</h3>
            <p:pickList value="#{purposeAddBean.detergents}"
                        var="detergent"
                        itemLabel="#{detergent.detergentShortName}"
                        itemValue="#{detergent}"
                        converter="genericPickListConverter"/>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/purposes/edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">


    <ui:define name="content">
        <h1>#{msg['label_purpose_edit_title']}</h1>
        <h:form>
            <h:panelGrid columns="2">
                <h:outputLabel for="purposeName">#{msg['label_purpose_name']}
                </h:outputLabel>
                <p:inputText id="purposeName" value="#{purposeEditBean.purpose.purposeName}"/>
            </h:panelGrid>
            <h3>#{msg['label_purpose_detergents']}:</h3>
            <p:pickList value="#{purposeEditBean.detergents}"
                        var="detergent"
                        itemLabel="#{detergent.detergentShortName}"
                        itemValue="#{detergent}"
                        converter="genericPickListConverter"/>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/purposes/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://
www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h:form id="formTable">
            <h:panelGrid columns="1">
                <p:commandButton value="#{msg['label_button_add']}" icon="ui-icon-plus" action="add"/>
                <p:dataTable var="purpose"
                             value="#{purposeListBean.purposes}"
                             paginator="true"
                             rows="10"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}
                                {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15"
                             rowKey="#{purpose.id}"
                             selectionMode="single"
                             selection="#{purposeListBean.selectedPurpose}"
                             sortBy="#{purpose.id}"
                             editable="true"
                             editMode="row"
                             resizableColumns="true">

                    <f:facet name="header">
                        #{msg['label_purpose_list']}
                    </f:facet>

                    <p:ajax event="rowEdit" listener="#{purposeListBean.onRowEdit}"/>

                    <p:column sortBy="#{purpose.id}"
                              headerText="#{msg['label_purpose_id']}"
                              style="width: 60px">
                        <h:outputText value="#{purpose.id}"/>
                    </p:column>

                    <p:column sortBy="#{purpose.purposeName}"
                              headerText="#{msg['label_purpose_name']}">
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{purpose.purposeName}"/>
                            </f:facet>
                            <f:facet name="input">
                                <p:inputText value="#{purpose.purposeName}"/>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column style="width:32px">
                        <p:rowEditor/>
                    </p:column>

                    <p:column style="width:32px">
                        <p:commandButton icon="ui-icon-trash"
                                         title="#{msg['label_purpose_delete_this']}"
                                         actionListener="#{purposeListBean.removePurpose(purpose)}"
                                         ajax="true"
                                         update=":formTable"
                                         style="width:30px; height:20px"
                                />
                    </p:column>

                    <f:facet name="footer">
                        <div align="left">
                            <p:commandButton value="#{msg['label_button_view']}" icon="ui-icon-search" action="view"/>
                            <p:commandButton value="#{msg['label_button_edit']}" icon="ui-icon-pencil" action="edit"/>
                        </div>
                    </f:facet>
                </p:dataTable>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/purposes/view.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">


    <ui:define name="content">
        <h1>Purpose</h1>
        <h:form >
            <h3>
                <h:outputText value="#{msg['label_purpose_name']}: "/>
                <h:outputText value="#{purposeViewBean.purpose.purposeName}"/>
            </h3>
            <h3>#{msg['label_purpose_detergents']}</h3>
            <p:dataList value="#{purposeViewBean.purpose.detergentsAsList}" var="detergent">
                #{detergent.detergentShortName}
            </p:dataList>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>