src/main/java/ru/netlly/technologymap/domain/Area.java
package ru.netlly.technologymap.domain;

import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "AREA")
public class Area implements Serializable, Convertible {
    private Long id;
    private String areaName;
    private Set<Purpose> purposes;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "AREA_NAME")
    @Size(min = 3, max = 80, message = "{validation.area.AreaName.Size.message}")
    @NotEmpty(message = "{validation.area.AreaName.NotEmpty.message}")
    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    @ManyToMany
    @JoinTable(
            name = "AREA_PURPOSE_RELATION",
            joinColumns = @JoinColumn(name = "AREA_ID"),
            inverseJoinColumns = @JoinColumn(name = "PURPOSE_ID")
    )
    public Set<Purpose> getPurposes() {
        return purposes;
    }

    public void setPurposes(Set<Purpose> purposes) {
        this.purposes = purposes;
    }

    @Transient
    public List<Purpose> getPurposesAsList() {
        return new ArrayList<Purpose>(purposes);
    }

    @Override
    public String toString() {
        return "Area{" +
                "id=" + id +
                ", areaName='" + areaName + '\'' +
                '}';
    }
}

src/main/java/ru/netlly/technologymap/domain/Convertible.java
package ru.netlly.technologymap.domain;

public interface Convertible {
    public Long getId();
}

src/main/java/ru/netlly/technologymap/domain/TechnologyMap.java
package ru.netlly.technologymap.domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "TECHNOLOGYMAP")
public class TechnologyMap implements Serializable, Convertible{
    private Long id;
    private AreaColor areaColor1;
    private AreaColor areaColor2;
    private Area area;
    private Purpose purpose;
    private Detergent detergent;
    private Dosage dosage;
    private Set<TechMapUsage> techMapUsages =
            new HashSet<TechMapUsage>();
    private Periodicity periodicity;
    private Temperature temperature;
    private ExpoTime expoTime;
    private Siz siz;

    public TechnologyMap() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @OneToOne
    @JoinColumn(name = "AREACOLOR1_ID")
    public AreaColor getAreaColor1() {
        return areaColor1;
    }

    public void setAreaColor1(AreaColor areaColor1) {
        this.areaColor1 = areaColor1;
    }

    @OneToOne
    @JoinColumn(name = "AREACOLOR2_ID")
    public AreaColor getAreaColor2() {
        return areaColor2;
    }

    public void setAreaColor2(AreaColor areaColor2) {
        this.areaColor2 = areaColor2;
    }

    @OneToOne
    @JoinColumn(name = "AREA_ID")
    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    @OneToOne
    @JoinColumn(name = "PURPOSE_ID")
    public Purpose getPurpose() {
        return purpose;
    }

    public void setPurpose(Purpose purpose) {
        this.purpose = purpose;
    }

    @OneToOne
    @JoinColumn(name = "DETERGENT_ID")
    public Detergent getDetergent() {
        return detergent;
    }

    public void setDetergent(Detergent detergent) {
        this.detergent = detergent;
    }

    @OneToOne
    @JoinColumn(name = "DOSAGE_ID")
    public Dosage getDosage() {
        return dosage;
    }

    public void setDosage(Dosage dosage) {
        this.dosage = dosage;
    }

    @OneToMany(mappedBy = "pk.technologyMap", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @OrderBy("ORDERNO")
    public Set<TechMapUsage> getTechMapUsages() {
        return techMapUsages;
    }

    public void setTechMapUsages(Set<TechMapUsage> techMapUsages) {
        this.techMapUsages = techMapUsages;
    }

    @Transient
    public String getUsagesAsString() {
        StringBuilder stringBuilder = new StringBuilder();
        for (TechMapUsage techMapUsage : getTechMapUsages()) {
            if (stringBuilder.length() == 0) {
                stringBuilder.append(techMapUsage.getOrderNo());
                stringBuilder.append(". ");
                stringBuilder.append(techMapUsage.getUsage().getUsageName());
            } else {
                stringBuilder.append("<br/>");
                stringBuilder.append(techMapUsage.getOrderNo());
                stringBuilder.append(". ");
                stringBuilder.append(techMapUsage.getUsage().getUsageName());
            }
        }
        return stringBuilder.toString();
    }

    @OneToOne
    @JoinColumn(name = "PERIODICITY_ID")
    public Periodicity getPeriodicity() {
        return periodicity;
    }

    public void setPeriodicity(Periodicity periodicity) {
        this.periodicity = periodicity;
    }

    @OneToOne
    @JoinColumn(name = "TEMPERATURE_ID")
    public Temperature getTemperature() {
        return temperature;
    }

    public void setTemperature(Temperature temperature) {
        this.temperature = temperature;
    }

    @OneToOne
    @JoinColumn(name = "EXPOTIME_ID")
    public ExpoTime getExpoTime() {
        return expoTime;
    }

    public void setExpoTime(ExpoTime expoTime) {
        this.expoTime = expoTime;
    }

    @OneToOne
    @JoinColumn(name = "SIZ_ID")
    public Siz getSiz() {
        return siz;
    }

    public void setSiz(Siz siz) {
        this.siz = siz;
    }

    @Override
    public String toString() {
        return "TechnologyMap{" +
                "id=" + id +
                ", areaColor1=" + areaColor1 +
                ", areaColor2=" + areaColor2 +
                ", area=" + area +
                ", purpose=" + purpose +
                ", detergent=" + detergent +
                ", dosage=" + dosage +
                ", techMapUsages=" + techMapUsages +
                ", periodicity=" + periodicity +
                ", temperature=" + temperature +
                ", expoTime=" + expoTime +
                ", siz=" + siz +
                '}';
    }
}

src/main/java/ru/netlly/technologymap/web/view/AreaAddBean.java
package ru.netlly.technologymap.web.view;

import org.primefaces.model.DualListModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.netlly.technologymap.domain.Area;
import ru.netlly.technologymap.domain.Purpose;
import ru.netlly.technologymap.service.PurposeService;
import ru.netlly.technologymap.service.AreaService;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

@Component
@Scope("session")
public class AreaAddBean implements Serializable{
    private Area area;
    private DualListModel<Purpose> purposes;

    @Autowired
    private AreaService areaService;

    @Autowired
    private PurposeService purposeService;

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public DualListModel<Purpose> getPurposes() {
        return purposes;
    }

    public void setPurposes(DualListModel<Purpose> purposes) {
        this.purposes = purposes;
    }

    public void init() {
        area = new Area();

        List<Purpose> purposesSource = new ArrayList<Purpose>();
        List<Purpose> purposesTarget = new ArrayList<Purpose>();
        for (Purpose p : purposeService.findAll()) {
            purposesSource.add(p);
        }
        purposes = new DualListModel<Purpose>(purposesSource, purposesTarget);
    }

    public void save() {
        area.setPurposes(new HashSet<Purpose>(purposes.getTarget()));
        areaService.save(area);
    }
}

src/main/java/ru/netlly/technologymap/web/view/AreaColorListBean.java
package ru.netlly.technologymap.web.view;

import org.primefaces.event.RowEditEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.netlly.technologymap.domain.AreaColor;
import ru.netlly.technologymap.service.AreaColorService;

import java.util.List;

@Component
@Scope("session")
public class AreaColorListBean {
    private List<AreaColor> areaColors;
    private AreaColor selectedAreaColor;
    private String addAreaColorName;
    private String addAreaColorValue;

    @Autowired
    private AreaColorService areaColorService;

    public List<AreaColor> getAreaColors() {
        return areaColors;
    }

    public void setAreaColors(List<AreaColor> areaColors) {
        this.areaColors = areaColors;
    }

    public AreaColor getSelectedAreaColor() {
        return selectedAreaColor;
    }

    public void setSelectedAreaColor(AreaColor selectedAreaColor) {
        this.selectedAreaColor = selectedAreaColor;
    }

    public String getAddAreaColorName() {
        return addAreaColorName;
    }

    public void setAddAreaColorName(String addAreaColorName) {
        this.addAreaColorName = addAreaColorName;
    }

    public String getAddAreaColorValue() {
        return addAreaColorValue;
    }

    public void setAddAreaColorValue(String addAreaColorValue) {
        this.addAreaColorValue = addAreaColorValue;
    }

    public void init() {
        areaColors = areaColorService.findAll();
    }

    public void addAreaColor() {
        AreaColor areaColor = new AreaColor(addAreaColorName, addAreaColorValue);
        areaColor = areaColorService.save(areaColor);
        areaColors.add(areaColor);

        addAreaColorName = null;
        addAreaColorValue = null;
    }

    public void onRowEdit(RowEditEvent event) {
        AreaColor areaColor = (AreaColor) event.getObject();
        areaColorService.save(areaColor);
    }

    public void removeAreaColor(AreaColor areaColor) {
        areaColorService.deleteById(areaColor.getId());
        areaColors.remove(areaColor);
    }
}

src/main/java/ru/netlly/technologymap/web/view/AreaEditBean.java
package ru.netlly.technologymap.web.view;

import org.primefaces.model.DualListModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.webflow.execution.RequestContext;
import ru.netlly.technologymap.domain.Purpose;
import ru.netlly.technologymap.domain.Area;
import ru.netlly.technologymap.service.PurposeService;
import ru.netlly.technologymap.service.AreaService;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

@Component
@Scope("session")
public class AreaEditBean implements Serializable{

    private Area area;
    private DualListModel<Purpose> purposes;

    @Autowired
    private AreaService areaService;

    @Autowired
    private PurposeService purposeService;

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public DualListModel<Purpose> getPurposes() {
        return purposes;
    }

    public void setPurposes(DualListModel<Purpose> purposes) {
        this.purposes = purposes;
    }

    public void init(RequestContext context) {

        Long id = context.getRequestScope().getLong("areaEditId");
        area = areaService.findByIdWithRelation(id);

        List<Purpose> purposesSource = new ArrayList<Purpose>();
        List<Purpose> purposesTarget = new ArrayList<Purpose>();
        for (Purpose purpose : area.getPurposes()) {
            purposesTarget.add(purpose);
        }
        for (Purpose purpose : purposeService.findAll()) {
            if (!(purposesTarget.contains(purpose))) {
                purposesSource.add(purpose);
            }
        }
        purposes = new DualListModel<Purpose>(purposesSource, purposesTarget);
    }

    public void save() {
        area.setPurposes(new HashSet<Purpose>(purposes.getTarget()));
        areaService.save(area);
    }
}

src/main/java/ru/netlly/technologymap/web/view/AreaListBean.java
package ru.netlly.technologymap.web.view;

import org.primefaces.event.RowEditEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.netlly.technologymap.domain.Area;
import ru.netlly.technologymap.service.AreaService;

import java.io.Serializable;
import java.util.List;

@Component
@Scope("session")
public class AreaListBean implements Serializable{
    private List<Area> areas;
    private Area selectedArea;

    @Autowired
    private AreaService areaService;

    public List<Area> getAreas() {
        return areas;
    }

    public void setAreas(List<Area> areas) {
        this.areas = areas;
    }

    public Area getSelectedArea() {
        return selectedArea;
    }

    public void setSelectedArea(Area selectedArea) {
        this.selectedArea = selectedArea;
    }

    public void init() {
        areas = areaService.findAll();
    }

    public void removeArea(Area area) {
        areaService.deleteById(area.getId());
        areas.remove(area);
    }

    public void onRowEdit(RowEditEvent event) {
        Area area = (Area) event.getObject();
        areaService.save(area);
    }
}

src/main/java/ru/netlly/technologymap/web/view/AreaViewBean.java
package ru.netlly.technologymap.web.view;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.webflow.execution.RequestContext;
import ru.netlly.technologymap.domain.Area;
import ru.netlly.technologymap.service.AreaService;

import java.io.Serializable;

@Component
@Scope("session")
public class AreaViewBean implements Serializable{
    private Area area;

    @Autowired
    private AreaService areaService;

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public void init(RequestContext requestContext) {
        Long id = requestContext.getRequestScope().getLong("areaViewId");
        area = areaService.findByIdWithRelation(id);
    }
}

src/main/java/ru/netlly/technologymap/web/view/DetergentAddBean.java
package ru.netlly.technologymap.web.view;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.DualListModel;
import org.primefaces.model.StreamedContent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import ru.netlly.technologymap.domain.Detergent;
import ru.netlly.technologymap.domain.Dosage;
import ru.netlly.technologymap.service.DetergentService;
import ru.netlly.technologymap.service.DosageService;

import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import java.io.ByteArrayInputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

@Component
@Scope("session")
public class DetergentAddBean implements Serializable{
    private static final Logger logger = LoggerFactory.getLogger(DetergentAddBean.class);

    private Detergent detergent;
    private DualListModel<Dosage> dosages;

    @Autowired
    private DetergentService detergentService;

    @Autowired
    private DosageService dosageService;

    public Detergent getDetergent() {
        return detergent;
    }

    public void setDetergent(Detergent detergent) {
        this.detergent = detergent;
    }

    public DualListModel<Dosage> getDosages() {
        return dosages;
    }

    public void setDosages(DualListModel<Dosage> dosages) {
        this.dosages = dosages;
    }

    public StreamedContent getImage() {

        FacesContext facesContext = FacesContext.getCurrentInstance();

        if (facesContext.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            return new DefaultStreamedContent();
        } else {
            return new DefaultStreamedContent(new ByteArrayInputStream(detergent.getImage()));
        }
    }

    public void handleFileUpload(FileUploadEvent event) {
        detergent.setImage(event.getFile().getContents());

        logger.info("handleFileUpload: Save photo with size: {}", detergent.getImage().length);
    }

    public void init() {
        detergent = new Detergent();

        List<Dosage> dosagesSource = new ArrayList<Dosage>();
        List<Dosage> dosagesTarget = new ArrayList<Dosage>();
        for (Dosage dosage : dosageService.findAll()) {
            dosagesSource.add(dosage);
        }
        dosages = new DualListModel<Dosage>(dosagesSource, dosagesTarget);
    }

    public void save() {
        detergent.setDosages(new HashSet<Dosage>(dosages.getTarget()));
        detergentService.save(detergent);
    }
}

src/main/webapp/WEB-INF/flows/technologymap/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://
www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">

    <ui:define name="content">

        <p:growl id="msgs" showDetail="true"/>

        <h:form id="formTable">
            <h:panelGrid columns="1">
                <p:commandButton value="#{msg['label_technologymap_add']}" icon="ui-icon-plus" action="add"/>
                <p:dataTable id="superDataTable"
                             var="technologyMap"
                             value="#{technologyMapListBean.technologyMaps}"
                             paginator="true"
                             rows="10"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}
                                {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15"
                             rowKey="#{technologyMap.id}"
                             selectionMode="single"
                             selection="#{technologyMapListBean.selectedTechnologyMap}"
                             editable="false"
                             sortBy="#{technologyMap.id}"
                             resizableColumns="true"
                        >

                    <f:facet name="header">
                        #{msg['label_technologymap_list']}
                    </f:facet>

                    <p:columnGroup type="header">
                        <p:row>
                            <p:column headerText="#{msg['label_technologymap_id']}" sortBy="#{technologyMap.id}"
                                      width="20"/>

                            <p:column width="20"
                                      style="height: 140px;">
                                <f:facet name="header">
                                    <div style="padding-top: 80px">
                                        <div style="-moz-transform: rotate(-90deg); -webkit-transform: rotate(-90deg);">
                                            <h:outputText value="#{msg['label_technologymap_clean_area']}"/>
                                        </div>
                                    </div>
                                </f:facet>
                            </p:column>

                            <p:column headerText="#{msg['label_technologymap_purpose']}"/>

                            <p:column colspan="2" headerText="#{msg['label_technologymap_detergent']}"/>

                            <p:column colspan="2" headerText="#{msg['label_technologymap_dosage']}"/>

                            <p:column headerText="#{msg['label_technologymap_usages']}" width="150"/>

                            <p:column headerText="#{msg['label_technologymap_periodicity']}"/>

                            <p:column style="white-space: normal;"
                                      headerText="#{msg['label_technologymap_temperature']} / #{msg['label_technologymap_ExpoTime']} / #{msg['label_technologymap_siz']}"/>

                            <p:column width="32"/>
                        </p:row>
                    </p:columnGroup>

                    <p:column>
                        <h:outputText value="#{technologyMap.id}"/>
                    </p:column>

                    <p:column
                            style="background: -moz-linear-gradient(##{technologyMap.areaColor1.areaColorValue} 50%,##{technologyMap.areaColor2.areaColorValue} 50%);
                              background: -webkit-linear-gradient(##{technologyMap.areaColor1.areaColorValue} 50%,##{technologyMap.areaColor2.areaColorValue} 50%);">
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText value="#{technologyMap.purpose.purposeName}"/>
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText value="#{technologyMap.detergent.detergentName}"/>
                    </p:column>

                    <p:column style="text-align: center">
                        <p:graphicImage value="#{imageStreamBean.detergentImage}" width="60" cache="false">
                            <f:param value="#{technologyMap.detergent.id}" name="detergentId"/>
                        </p:graphicImage>
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText value="#{technologyMap.dosage.dosageContent}"/>
                    </p:column>

                    <p:column style="text-align: center">
                        <p:graphicImage value="#{imageStreamBean.dosageImage}" width="60" cache="false">
                            <f:param value="#{technologyMap.dosage.id}" name="dosageId"/>
                        </p:graphicImage>
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText value="#{technologyMap.usagesAsString}" escape="false"/>
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText value="#{technologyMap.periodicity.periodicityName}"/>
                    </p:column>

                    <p:column style="white-space: normal;">
                        <h:outputText
                                value="#{technologyMap.temperature.temperatureValue} / #{technologyMap.expoTime.expoTimeValue} / #{technologyMap.siz.sizName}"/>
                    </p:column>

                    <p:column>
                        <p:commandButton icon="ui-icon-trash"
                                         title="#{msg['label_technologymap_delete_this']}"
                                         actionListener="#{technologyMapListBean.removeTechnologyMap(technologyMap)}"
                                         ajax="true"
                                         update=":formTable"
                                         style="width:30px; height:20px"
                                />
                    </p:column>

                </p:dataTable>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>