src/main/java/ru/netlly/technologymap/domain/Detergent.java
package ru.netlly.technologymap.domain;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "DETERGENT")
public class Detergent implements Serializable, Convertible{
    private Long id;
    private String detergentShortName;
    private String detergentName;
    private byte[] image;
    private Set<Purpose> purposes = new HashSet<Purpose>();
    private Set<Dosage> dosages = new HashSet<Dosage>();

    public Detergent() {
    }

    public Detergent(String detergentShortName) {
        this.detergentShortName = detergentShortName;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "DETERGENT_SHORT_NAME")
    @Size(min=3, max = 80, message = "{validation.detergent.DetergentShortName.Size.message}")
    @NotEmpty(message = "{validation.detergent.DetergentShortName.NotEmpty.message}")
    public String getDetergentShortName() {
        return detergentShortName;
    }

    public void setDetergentShortName(String detergentShortName) {
        this.detergentShortName = detergentShortName;
    }

    @Column(name = "DETERGENT_NAME")
    @Size(min = 3, max = 80, message = "{validation.detergent.DetergentName.Size.message}")
    @NotEmpty(message = "{validation.detergent.DetergentName.NotEmpty.message}")
    public String getDetergentName() {
        return detergentName;
    }

    public void setDetergentName(String detergentName) {
        this.detergentName = detergentName;
    }

    @Column(name = "IMAGE")
    @Basic(fetch = FetchType.LAZY)
    @Lob
    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @ManyToMany
    @JoinTable(name = "PURPOSE_DETERGENT_RELATION",
    joinColumns = @JoinColumn(name = "DETERGENT_ID"),
    inverseJoinColumns = @JoinColumn(name = "PURPOSE_ID"))
    public Set<Purpose> getPurposes() {
        return purposes;
    }

    public void setPurposes(Set<Purpose> purposes) {
        this.purposes = purposes;
    }

    @ManyToMany
    @JoinTable(
            name = "DETERGENT_DOSAGE_RELATION",
            joinColumns = @JoinColumn(name = "DETERGENT_ID"),
            inverseJoinColumns = @JoinColumn(name = "DOSAGE_ID")
    )
    public Set<Dosage> getDosages() {
        return dosages;
    }

    public void setDosages(Set<Dosage> dosages) {
        this.dosages = dosages;
    }

    @Transient
    public List<Dosage> getDosagesAsList() {
        return new ArrayList<Dosage>(dosages);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        Detergent detergent = (Detergent) o;

        return new EqualsBuilder()
                .append(id, detergent.id)
                .append(detergentShortName, detergent.detergentShortName)
                .append(detergentName, detergent.detergentName)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
                .append(id)
                .append(detergentShortName)
                .append(detergentName)
                .toHashCode();
    }

    @Override
    public String toString() {
        return "Detergent{" +
                "id=" + id +
                ", detergentShortName='" + detergentShortName + '\'' +
                ", detergentName='" + detergentName + '\'' +
                '}';
    }
}

src/main/webapp/WEB-INF/flows/detergents/add.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h1>#{msg['label_detergent_add_title']}</h1>
        <h:form enctype="multipart/form-data">
            <h:panelGrid columns="2">
                <h:outputLabel for="detergentShortName">#{msg['label_detergent_short_name']}
                </h:outputLabel>
                <p:inputText id="detergentShortName" value="#{detergentAddBean.detergent.detergentShortName}"/>
            </h:panelGrid>
            <h:panelGrid columns="2">
                <h:outputLabel for="detergentName">#{msg['label_detergent_name']}
                </h:outputLabel>
                <p:inputText id="detergentName" value="#{detergentAddBean.detergent.detergentName}"/>
            </h:panelGrid>
            <h3>#{msg['label_detergent_dosages']}:</h3>
            <p:pickList value="#{detergentAddBean.dosages}"
                        var="dosage"
                        itemLabel="#{dosage.dosageContent}"
                        itemValue="#{dosage}"
                        converter="genericPickListConverter"/>
            <h3>#{msg['label_detergent_image']}:</h3>
            <p:fileUpload fileUploadListener="#{detergentAddBean.handleFileUpload}"
                          allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
                          previewWidth="200"
                          mode="advanced"
                          sizeLimit="1000000"
                          multiple="false"
                          auto="true"
                          update="uploadedPhoto"
                          label="#{msg['label_button_choose']}"
                    />
            <p:graphicImage
                    id="uploadedPhoto"
                    value="#{detergentAddBean.image}"
                    cache="false"
                    />
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/detergents/edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h1>#{msg['label_detergent_edit_title']}</h1>
        <h:form enctype="multipart/form-data">
            <h:panelGrid columns="2">
                <h:outputLabel for="detergentShortName">#{msg['label_detergent_short_name']}
                </h:outputLabel>
                <p:inputText id="detergentShortName" value="#{detergentEditBean.detergent.detergentShortName}"/>
            </h:panelGrid>
            <h:panelGrid columns="2">
                <h:outputLabel for="detergentName">#{msg['label_detergent_name']}
                </h:outputLabel>
                <p:inputText id="detergentName" value="#{detergentEditBean.detergent.detergentName}"/>
            </h:panelGrid>
            <h3>#{msg['label_detergent_dosages']}:</h3>
            <p:pickList value="#{detergentEditBean.dosages}"
                        var="dosage"
                        itemLabel="#{dosage.dosageContent}"
                        itemValue="#{dosage}"
                        converter="genericPickListConverter"/>
            <h3>#{msg['label_detergent_image']}:</h3>
            <p:fileUpload fileUploadListener="#{detergentEditBean.handleFileUpload}"
                          allowTypes="/(\.|\/)(gif|jpe?g|png)$/"
                          previewWidth="200"
                          mode="advanced"
                          sizeLimit="1000000"
                          multiple="false"
                          auto="true"
                          update="uploadedPhoto"
                          label="#{msg['label_button_choose']}"
                    />
            <p:graphicImage
                    id="uploadedPhoto"
                    value="#{detergentEditBean.image}"
                    cache="false"
                    />
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/detergents/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://
www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h:form id="formTable">
            <h:panelGrid columns="1">
                <p:commandButton value="#{msg['label_detergent_add']}" icon="ui-icon-plus" action="add"/>
                <p:dataTable var="detergent"
                             value="#{detergentListBean.detergents}"
                             paginator="true"
                             rows="10"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}
                                {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15"
                             rowKey="#{detergent.id}"
                             selectionMode="single"
                             selection="#{detergentListBean.selectedDetergent}"
                             sortBy="#{detergent.id}"
                             editable="true"
                             editMode="row"
                             resizableColumns="true">

                    <f:facet name="header">
                        #{msg['label_detergent_list']}
                    </f:facet>

                    <p:ajax event="rowEdit" listener="#{detergentListBean.onRowEdit}"/>

                    <p:column sortBy="#{detergent.id}"
                              headerText="#{msg['label_detergent_id']}"
                              style="width: 60px">
                        <h:outputText value="#{detergent.id}"/>
                    </p:column>

                    <p:column sortBy="#{detergent.detergentShortName}"
                              headerText="#{msg['label_detergent_name']}"
                              style="white-space: normal;">
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{detergent.detergentShortName}" />
                            </f:facet>
                            <f:facet name="input">
                                <p:inputText value="#{detergent.detergentShortName}" />
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column style="width:32px">
                        <p:rowEditor/>
                    </p:column>

                    <p:column style="width:32px">
                        <p:commandButton icon="ui-icon-trash"
                                         title="#{msg['label_detergent_delete_this']}"
                                         actionListener="#{detergentListBean.removeDetergent(detergent)}"
                                         ajax="true"
                                         update=":formTable"
                                         style="width:30px; height:20px"
                                />
                    </p:column>

                    <f:facet name="footer">
                        <div align="left">
                            <p:commandButton value="#{msg['label_button_view']}" icon="ui-icon-search" action="view" />
                            <p:commandButton value="#{msg['label_button_edit']}" icon="ui-icon-pencil" action="edit" />
                        </div>
                    </f:facet>
                </p:dataTable>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/detergents/view.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">


    <ui:define name="content">
        <h1>#{msg['label_detergent_detergent']}</h1>
        <h:form >
            <h3>
                <h:outputText value="#{msg['label_detergent_short_name']}: "/>
                <h:outputText value="#{detergentViewBean.detergent.detergentShortName}"/>
            </h3>
            <h3>
                <h:outputText value="#{msg['label_detergent_name']}: "/>
                <h:outputText value="#{detergentViewBean.detergent.detergentName}"/>
            </h3>
            <h3>#{msg['label_detergent_dosages']}:</h3>
            <p:dataList value="#{detergentViewBean.detergent.dosagesAsList}" var="dosage">
                #{dosage.dosageContent}
            </p:dataList>
            <h3>#{msg['label_detergent_image']}:</h3>
            <p:graphicImage value="#{detergentViewBean.image}" cache="false"/>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>