src/main/java/ru/netlly/technologymap/domain/Area.java
package ru.netlly.technologymap.domain;

import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@Entity
@Table(name = "AREA")
public class Area implements Serializable, Convertible {
    private Long id;
    private String areaName;
    private Set<Purpose> purposes;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "AREA_NAME")
    @Size(min = 3, max = 80, message = "{validation.area.AreaName.Size.message}")
    @NotEmpty(message = "{validation.area.AreaName.NotEmpty.message}")
    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    @ManyToMany
    @JoinTable(
            name = "AREA_PURPOSE_RELATION",
            joinColumns = @JoinColumn(name = "AREA_ID"),
            inverseJoinColumns = @JoinColumn(name = "PURPOSE_ID")
    )
    public Set<Purpose> getPurposes() {
        return purposes;
    }

    public void setPurposes(Set<Purpose> purposes) {
        this.purposes = purposes;
    }

    @Transient
    public List<Purpose> getPurposesAsList() {
        return new ArrayList<Purpose>(purposes);
    }

    @Override
    public String toString() {
        return "Area{" +
                "id=" + id +
                ", areaName='" + areaName + '\'' +
                '}';
    }
}

src/main/webapp/WEB-INF/flows/areas/add.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h1>#{msg['label_area_add_title']}</h1>
        <h:form enctype="multipart/form-data">
            <h:panelGrid columns="2">
                <h:outputLabel for="areaName">#{msg['label_area_name']}
                </h:outputLabel>
                <p:inputText id="areaName" value="#{areaAddBean.area.areaName}"/>
            </h:panelGrid>
            <h3>#{msg['label_area_purposes']}:</h3>
            <p:pickList value="#{areaAddBean.purposes}"
                        var="purpose"
                        itemLabel="#{purpose.purposeName}"
                        itemValue="#{purpose}"
                        converter="genericPickListConverter"/>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/areas/edit.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h1>#{msg['label_area_edit_title']}</h1>
        <h:form enctype="multipart/form-data">
            <h:panelGrid columns="2">
                <h:outputLabel for="areaName">#{msg['label_area_name']}
                </h:outputLabel>
                <p:inputText id="areaName" value="#{areaEditBean.area.areaName}"/>
            </h:panelGrid>
            <h3>#{msg['label_area_purposes']}:</h3>
            <p:pickList value="#{areaEditBean.purposes}"
                        var="purpose"
                        itemLabel="#{purpose.purposeName}"
                        itemValue="#{purpose}"
                        converter="genericPickListConverter"/>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit" immediate="true"/>
                    <p:commandButton value="#{msg['label_button_save']}" icon="ui-icon-check" action="save"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/areas/list.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://
www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">
    <ui:define name="content">
        <h:form id="formTable">
            <h:panelGrid columns="1">
                <p:commandButton value="#{msg['label_area_add']}" icon="ui-icon-plus" action="add"/>
                <p:dataTable var="area"
                             value="#{areaListBean.areas}"
                             paginator="true"
                             rows="10"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink}
                                {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}
                                {RowsPerPageDropdown}"
                             rowsPerPageTemplate="5,10,15"
                             rowKey="#{area.id}"
                             selectionMode="single"
                             selection="#{areaListBean.selectedArea}"
                             sortBy="#{area.id}"
                             editable="true"
                             editMode="row"
                             resizableColumns="true">

                    <f:facet name="header">
                        #{msg['label_area_list']}
                    </f:facet>

                    <p:ajax event="rowEdit" listener="#{areaListBean.onRowEdit}"/>

                    <p:column sortBy="#{area.id}"
                              headerText="#{msg['label_area_id']}"
                              style="width: 60px">
                        <h:outputText value="#{area.id}"/>
                    </p:column>

                    <p:column sortBy="#{area.areaName}"
                              headerText="#{msg['label_area_name']}">
                        <p:cellEditor>
                            <f:facet name="output">
                                <h:outputText value="#{area.areaName}" />
                            </f:facet>
                            <f:facet name="input">
                                <p:inputText value="#{area.areaName}" />
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column style="width:32px">
                        <p:rowEditor/>
                    </p:column>

                    <p:column style="width:32px">
                        <p:commandButton icon="ui-icon-trash"
                                         title="#{msg['label_area_delete_this']}"
                                         actionListener="#{areaListBean.removeArea(area)}"
                                         ajax="true"
                                         update=":formTable"
                                         style="width:30px; height:20px"
                                />
                    </p:column>

                    <f:facet name="footer">
                        <div align="left">
                            <p:commandButton value="#{msg['label_button_view']}" icon="ui-icon-search" action="view" />
                            <p:commandButton value="#{msg['label_button_edit']}" icon="ui-icon-pencil" action="edit" />
                        </div>
                    </f:facet>
                </p:dataTable>
            </h:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/WEB-INF/flows/areas/view.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/layouts/standard.xhtml">


    <ui:define name="content">
        <h1>#{msg['label_area_area']}</h1>
        <h:form >
            <h3>
                <h:outputText value="#{msg['label_area_name']}: "/>
                <h:outputText value="#{areaViewBean.area.areaName}"/>
            </h3>
            <h3>#{msg['label_area_purposes']}:</h3>
            <p:dataList value="#{areaViewBean.area.purposesAsList}" var="purpose">
                #{purpose.purposeName}
            </p:dataList>
            <p:toolbar>
                <p:toolbarGroup align="left">
                    <p:commandButton value="#{msg['label_button_back']}" icon="ui-icon-arrowreturn-1-w" action="exit"/>
                </p:toolbarGroup>
            </p:toolbar>
        </h:form>
    </ui:define>
</ui:composition>